name: BitTrack CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            build-essential \
            libssl-dev \
            libcurl4-openssl-dev \
            zlib1g-dev \
            libgtest-dev
          # Build and install gtest
          cd /usr/src/googletest
          sudo cmake .
          sudo make
          sudo cp lib/*.a /usr/lib

      - name: Build project
        run: make build

      - name: Compile project
        run: make compile

      - name: Run tests
        run: make test

      - name: Clean up
        if: success()
        run: make clean
