name: BitTrack CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Install build dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            build-essential \
            libssl-dev \
            libcurl4-openssl-dev \
            zlib1g-dev

      - name: Build, Compile & Test
        run: |
          make build
          make compile
          make test

      - name: Cleanup artifacts
        if: success()
        run: make clean
